name: Data Sync Workflow
on:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  build:
    name: Data Sync Job
    runs-on: ubuntu-latest
    steps:
       - name: Checkout repo
         uses: actions/checkout@v2
       - name: Setup Python
         uses: actions/setup-python@v2
         with:
           python-version: 3.7
       - name: Cache pip
         uses: actions/cache@v2
         with:
           # This path is specific to Ubuntu
           path: ~/.cache/pip
           # Look to see if there is a cache hit for the corresponding requirements file
           key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
           restore-keys: |
             ${{ runner.os }}-pip-
             ${{ runner.os }}-
       - name: Install dependencies
         run: pip install -r requirements.txt
       - name: Execute sync
         run: |
           bash glide_covid_19/scripts/sync_all.sh
       - name: Commit
         run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "hourly sync"
          git push
